
var CONST = (function(){

	return{
		USER:{
			ROLE:{
				ADMIN: 'ADMIN',
				WRITER: 'WRITER'	
			},
			ERROR:{
				INVALID_EMAIL: 'USER.ERROR.INVALID_EMAIL',
				INVALID_PASSWORD: 'USER.ERROR.INVALID_PASSWORD',
				INVALID_FIRSTNAME: 'USER.ERROR.INVALID_FIRSTNAME',
				INVALID_LASTNAME: 'USER.ERROR.INVALID_LASTNAME',
				WRONG_EMAIL: 'USER.ERROR.WRONG_EMAIL',
				WRONG_EMAIL_AND_PASSWORD: 'USER.ERROR.WRONG_EMAIL_AND_PASSWORD',
				EXPIRED_JWT: 'USER.ERROR.EXPIRED_JWT'
			},
			SUCCESS:{
				AUTHENTICATION_GRANTED: 'USER.SUCCESS.AUTHENTICATION_GRANTED',
				DISCONNECTION: 'USER.SUCCESS.DISCONNECTION'
			}
		},
		POST:{
			ERROR:{
				INVALID_USER_ID: 'POST.ERROR.INVALID_USER_ID',
				INVALID_CATEGORY_ID: 'POST.ERROR.INVALID_CATEGORY_ID',
				INVALID_URL: 'POST.ERROR.INVALID_URL',
				INVALID_TITLE: 'POST.ERROR.INVALID_TITLE',
				INVALID_CONTENT: 'POST.ERROR.INVALID_CONTENT',
				IMG_CREATION_ERROR: 'POST.ERROR.IMG_CREATION_ERROR'
			},
			SUCCESS:{
				POST_RECORDED: 'POST.SUCCESS.POST_RECORDED',
				IMG_RECORDED: 'POST.SUCCESS.IMG_RECORDED'
			}
		},
		CATEGORY:{
			ERROR:{
				INVALID_CATEGORY_NAME: 'CATEGORY.ERROR.INVALID_CATEGORY_NAME'
			},
			SUCCESS:{
				CATEGORY_RECORDED: 'CATEGORY.SUCCESS.CATEGORY_RECORDED'
			}
		},
		MONGO:{
			EMPTY_SELECTION: 'MONGO.EMPTY_SELECTION',
			TECHNICAL_ERROR: 'MONGO.TECHNICAL_ERROR',
			EMAIL_ALREADY_EXIST: 'MONGO.EMAIL_ALREADY_EXIST',
			URL_ALREADY_EXIST: 'MONGO.URL_ALREADY_EXIST',
			USER_REGISTERED: 'MONGO.USER_REGISTERED',
			POST_REGISTERED: 'MONGO.POST_REGISTERED',
			USER_UPDATED: 'MONGO.USER_UPDATED',
			USER_DELETED: 'MONGO.USER_DELETED',
			POST_UPDATED: 'MONGO.POST_UPDATED',
			POST_DELETED: 'MONGO.POST_DELETED',
			CATEGORY_ALREADY_EXIST: 'MONGO.CATEGORY_ALREADY_EXIST',
			CATEGORY_UPDATED: 'MONGO.CATEGORY_UPDATED',
			CATEGORY_DELETED: 'MONGO.CATEGORY_DELETED'
		},
		COMMON:{
			TECHNICAL_ERROR: 'COMMON.TECHNICAL_ERROR',
			SESSION_EXPIRED: 'COMMON.SESSION_EXPIRED'
		}
	};

}());

module.exports = CONST;